{{- if .Values.gateway.createGatewayClass }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.gatewayClassName }}
spec:
  controllerName: example.com/gateway-controller
{{- end }}
