apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
